### ISSUE TITLE
Crashes when trying to connect

### ISSUE THREAD

**Issue by AndriyGo** [JSTPMobile/iOS#8]
I am trying to incorporate this library in my project and I am facing a very unfortunate issues.

After installing the framework through Carthage I cannot use the line

`let connection = JSTP.connect(host: "127.0.0.1", port: 3002)`

as the compiler cannot find a function connect.

I thought that I have found a workaround by doing:

`let connection = Connection(host: "127.0.0.1", port: 3002)`
`connection.delegate = self`
`connection.connect()`

However, after such modification the program crashes each time due to some socket related issues. Could you please assist me?

**Comment by GYFK** [comment]
@AndriyGo Did you try to use carthage update with --use-submodules flag?

**Comment by Gagnant** [comment]
@AndriyGo, I have updated docs to the latest changes , but a lot of functionality not yet listed there (will be fixed in future).  I made some changes so please update library with carthage,  hope it will solve your problem
