### ISSUE TITLE
cocoapods not working

### ISSUE THREAD

**Issue by Gagnant** [JSTPMobile/iOS#9]
<img width="304" alt="screen shot 2016-10-05 at 6 48 40 pm" src="https://cloud.githubusercontent.com/assets/4082760/19120712/71824ea0-8b2c-11e6-90c5-68492dc950bf.png">
@GYFK, fix or remove non working stuff

**Comment by GYFK** [comment]
@Gagnant It shouldn't work by now, the podspec file is unfinished yet due to the Socket.framework linking issues. Pod wasn't marked as ready to use.

**Comment by Gagnant** [comment]
@GYFK but if it isn't ready, please commit all pod related stuff to another brunch (e.g. Cocoapoding)

**Comment by Gagnant** [comment]
fixed with 8b5d948
